groupGo/apps/organizations/urls.py
from django.conf.urls import patterns, url
from apps.organizations.views import (
    MapView, AddOrgView, AddCarView, OrganizationListAPIView, OrganizationDetailAPIView,
    CarPoolerListAPIView, CarPoolerDetailAPIView, OrganizationCarPoolerAPIView
)


urlpatterns = patterns(
    '',
    url(r'^$', MapView.as_view(), name='map'),
    url(r'^addOrg$', AddOrgView.as_view(), name='addOrg'),
    url(r'^addCar$', AddCarView.as_view(), name='addCar'),
    url(
        r'^api/organizations$',
        OrganizationListAPIView.as_view(),
        name='api-organizations',
    ),
    url(
        r'^api/organizations/(?P<pk>\d+)$',
        OrganizationDetailAPIView.as_view(),
        name='api-organizations-detail',
    ),
    url(
        r'^api/organizations/(?P<pk>\d+)/carpoolers$',
        OrganizationCarPoolerAPIView.as_view(),
        name='api-organization-carpooler-detail',
    ),
    url(
        r'^api/carpoolers$',
        CarPoolerListAPIView.as_view(),
        name='api-carpoolers',
    ),
    url(
        r'^api/carpoolers/(?P<pk>\d+)$',
        CarPoolerDetailAPIView.as_view(),
        name='api-carpoolers-detail',
    ),
)

groupGo/groupGo/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns(
    '',
    url(r'^organizations/', include('apps.organizations.urls')),
    url(r'^organizations/add/', include('apps.organizations.urls'))
)

groupGo/apps/organizations/models.py
from django.db import models
import requests
import simplejson as json

GEOCODING_URL = "http://maps.googleapis.com/maps/api/geocode/json"


class Organization(models.Model):
    name = models.CharField(max_length=254)
    location = models.TextField()
    description = models.TextField()
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.latitude and not self.longitude:
            geocoded_blob = json.loads(requests.get(
                GEOCODING_URL,
                params={
                    "address": self.location,
                    "sensor": 'false'
                }
            ).content)

            location = geocoded_blob['results'][0]['geometry']['location']
            self.latitude = location['lat']
            self.longitude = location['lng']
        super(Organization, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class CarPooler(models.Model):
    name = models.CharField(max_length=254)
    arrival_time = models.TimeField()
    departure_time = models.TimeField()
    car_description = models.TextField()
    leaving_from = models.TextField()
    going_to = models.TextField()
    organization = models.ForeignKey(Organization, related_name="carpoolers")
    departure_latitude = models.FloatField(blank=True, null=True)
    departure_longitude = models.FloatField(blank=True, null=True)
    arrival_latitude = models.FloatField(blank=True, null=True)
    arrival_longitude = models.FloatField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.arrival_latitude and not self.arrival_longitude:
            geocoded_blob = json.loads(requests.get(
                GEOCODING_URL,
                params={
                    "address": self.going_to,
                    "sensor": 'false'
                }
            ).content)

            location = geocoded_blob['results'][0]['geometry']['location']
            self.arrival_latitude = location['lat']
            self.arrival_longitude = location['lng']

        if not self.departure_latitude and not self.departure_longitude:
            geocoded_blob = json.loads(requests.get(
                GEOCODING_URL,
                params={
                    "address": self.leaving_from,
                    "sensor": 'false'
                }
            ).content)

            location = geocoded_blob['results'][0]['geometry']['location']
            self.departure_latitude = location['lat']
            self.departure_longitude = location['lng']
        super(CarPooler, self).save(*args, **kwargs)

groupGo/apps/organizations/views.py
from django.views.generic import TemplateView, CreateView
from rest_framework import generics

from .models import Organization, CarPooler
from .serializers import OrganizationSerializer, CarPoolerSerializer


class MapView(TemplateView):
    template_name = "organizations/map.html"

class AddOrgView(CreateView):
    model = Organization
    template_name = "organizations/organization.html"
    success_url = "/organizations"

class AddCarView(CreateView):
    model = CarPooler
    template_name = "organizations/carpoolers.html"
    success_url = "/organizations"

class OrganizationListAPIView(generics.ListCreateAPIView):
    queryset = Organization.objects.all()
    serializer_class = OrganizationSerializer


class OrganizationDetailAPIView(generics.RetrieveUpdateDestroyAPIView):
    model = Organization
    serializer_class = OrganizationSerializer


class CarPoolerListAPIView(generics.ListCreateAPIView):
    queryset = CarPooler.objects.all()
    serializer_class = CarPoolerSerializer


class CarPoolerDetailAPIView(generics.RetrieveUpdateDestroyAPIView):
    model = CarPooler
    serializer_class = CarPoolerSerializer


class OrganizationCarPoolerAPIView(generics.ListAPIView):
    serializer_class = CarPoolerSerializer

    def get_queryset(self):
        return Organization.objects.get(pk=self.kwargs['pk']).carpoolers.all()

groupGo/apps/organizations/templates/organizations/carpoolers.html
{% extends "layouts/base.html" %}

{% block extra_js %}
<script data-main="{{ STATIC_URL }}js/app/application.js" src="{{ STATIC_URL }}js/bower_components/requirejs/require.js"></script>
{% endblock %}

{% block title %}
Add an Organization
{% endblock %}

{% block content %}
{% endblock %}

{% block more_content %}
<div class="section organization">
	<div class="container Organization">
		<form method="post">
			<div class="row">
				<div class="column size-12">
					<h1>Add a Car</h1>
				</div>
			</div>
			<div class="row">
				<div class="column size-6 shrink-right">
					<h2>Name</h2>
				</div>
				<div class="column size-6 shrink-left">
					<input id="id_name" class="expand" type="text" name="name">
				</div>
			</div>
			<div class="row">
				<div class="column size-6 shrink-right">
					<h2>Departure Time</h2>
				</div>
				<div class="column size-6 shrink-left">
					<input id="id_departure_time" class="expand" type="text" name="departure_time">
				</div>
			</div>
			<div class="row">
				<div class="column size-6 shrink-right">
					<h2>Car Description</h2>
				</div>
				<div class="column size-6 shrink-left">
					<textarea id="id_car_description" class="expandcar" name="car_description"></textarea>
				</div>
			</div>
			<div class="row">
				<div class="column size-6 shrink-right">
					<h2>Leaving From</h2>
				</div>
				<div class="column size-6 shrink-left">
					<textarea id="id_leaving_from" class="expandcar" name="leaving_from"></textarea>
				</div>
			</div>
			<div class="row">
				<div class="column size-6 shrink-right">
					<h2>Going To</h2>
				</div>
				<div class="column size-6 shrink-left">
					<textarea id="id_going_to" class="expandcar" name="going_to"></textarea>
				</div>
			</div>
			<div class="row">
				<div class="column size-6 shrink-right">
					<h2>Organization</h2>
				</div>
				<div class="column size-6 shrink-left">
					<select id="id_organization" class="expand" name="organization">
						{% for id, name in form.fields.organization.choices %}
							<option value="{{ id }}">{{ name }}</option>
						{% endfor %}
					</select>
				</div>
			</div>
			<div class="row">
				<div class="column size-12">
					<input class="button" type="submit" value="Add">
				</div>
			</div>
			{% csrf_token %}
			{{ form.errors }}
		</form>
	</div>
</div>
{% endblock %}

groupGo/apps/organizations/templates/organizations/map.html
{% extends "layouts/base.html" %}

{% block extra_js %}
<script data-main="{{ STATIC_URL }}js/app/application.js" src="{{ STATIC_URL }}js/bower_components/requirejs/require.js"></script>
<script src="{{ STATIC_URL }}js/bower_components/jquery/jquery.min.js"></script>

<script type="text/javascript">  
$(function(){
   setTimeout(function() {
      $("#splash").fadeOut("slow");
   }, 2000);
});
</script>
{% endblock %}

{% block title %}
Organization Map
{% endblock %}

{% block content %}
{% endblock %}

{% block more_content %}
<div id="splash" class="section splash">
	<div class="container splash">
		<img src="{{ STATIC_URL }}img/logo.png">
	</div>
</div>
{% endblock %}

groupGo/apps/organizations/templates/organizations/organization.html
{% extends "layouts/base.html" %}

{% block extra_js %}
<script data-main="{{ STATIC_URL }}js/app/application.js" src="{{ STATIC_URL }}js/bower_components/requirejs/require.js"></script>
{% endblock %}

{% block title %}
Add an Organization
{% endblock %}

{% block content %}
{% endblock %}

{% block more_content %}
<div class="section organization">
	<div class="container Organization">
		<form method="post">
			<div class="row">
				<div class="column size-12">
					<h1>Add an Organization</h1>
				</div>
			</div>
			<div class="row">
				<div class="column size-6 shrink-right">
					<h2>Name</h2>
				</div>
				<div class="column size-6 shrink-left">
					<input id="id_name" class="expand" type="text" name="name">
				</div>
			</div>
			<div class="row">
				<div class="column size-6 shrink-right">
					<h2>Location</h2>
				</div>
				<div class="column size-6 shrink-left">
					<input id="id_location" class="expand" type="text" name="location">
				</div>
			</div>
			<div class="row">
				<div class="column size-6 shrink-right">
					<h2 class="desc">Description</h2>
				</div>
				<div class="column size-6 shrink-left">
					<textarea id="id_description" class="expand" name="description"></textarea>
				</div>
			</div>
			<div class="row" style="display: none;">
				<div class="column size-6 shrink-right">
					<h2>Latitude</h2>
					<input id="id_latitude" class="expand" type="text" name="lat">
				</div>
				<div class="column size-6 shrink-left">
					<h2>Longitude</h2>
					<input id="id_longitude" class="expand" type="text" name="long">
				</div>
			</div>
			<div class="row">
				<div class="column size-12">
					<input class="button" type="submit" value="Add">
				</div>
			</div>
			{% csrf_token %}
			{{ form.errors }}
		</form>
	</div>
</div>
{% endblock %}

groupGo/templates/layouts/base.html
<!doctype html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{{ STATIC_URL }}css/groupgo.css" type="text/css" rel="stylesheet">
        <link href="{{ STATIC_URL }}css/groupgo-mediaqueries.css" type="text/css" rel="stylesheet">
        {% block extra_css %}
        {% endblock %}
    </head>
    <body>
        <div class="section header">
            <div class="container header">
                <a href="/organizations/addOrg" class="nav_link">Add an Org</a>
                <a href="/organizations" class="nav_link logo"><img class="logo" src="{{ STATIC_URL }}img/logo.png"></a>
                <a href="/organizations/addCar" class="nav_link">Add a Car</a>
            </div>
        </div>
        <div id="map-canvas" class="section map">
            {% block content %}
            {% endblock %}
        </div>
        {% block more_content %}
        {% endblock %}
        {% block extra_js %}
        {% endblock %}
    </body>
</html>